### ISSUE TITLE
Use Observables instead of Promises to fetch cards

### ISSUE THREAD

**Issue by kwk** [almighty/almighty-ui#10]
Hi,

I was trying to connect to the UI to the core using the core's REST API endpoint. That is when I stumpled over the `CardService.getCards()` method which returns a `Promise<Card[]>`. There seem to be quite some disadvantages when using a `Promise` compare to an `Observable`.

Consider these points (taken from [here](http://blog.thoughtram.io/angular/2016/01/06/taking-advantage-of-observables-in-angular2.html)):

1. **Don’t hit the search endpoint on every key stroke.**
Treat the search endpoint as if you pay for it on a per-request basis. No matter if it’s your own hardware or not. We shouldn’t be hammering the search endpoint more often than needed. Basically we only want to hit it once the user has stopped typing instead of with every keystroke.
2. **Don’t hit the search endpoint with the same query params for subsequent requests.**
Consider you type foo, stop, type another o, followed by an immediate backspace and rest back at foo. That should be just one request with the term foo and not two even if we technically stopped twice after we had foo in the search box.
3. **Deal with out-of-order responses.**
When we have multiple requests in-flight at the same time we must account for cases where they come back in unexpected order. Consider we first typed computer, stop, a request goes out, we type car, stop, a request goes out. Now we have two requests in-flight. Unfortunately the request that carries the results for computer comes back after the request that carries the results for car. This may happen because they are served by different servers. If we don’t deal with such cases properly we may end up showing results for computer whereas the search box reads car.

This 7 minute video gives a nice overview of why wants to use `Observables` over `Promises`: https://egghead.io/lessons/rxjs-rxjs-observables-vs-promises

I understand that his requires some changes to how card objects get filtered and passed around.

**Comment by joshuawilson** [comment]
@kwk 
Observables work great for something like Search but not for a single Get call. Maybe if we are trying to keep the list up to date then we can use Observables. It is also worth noting that we are using the Promise wrapper around Observables. We are not using a true Promise here. 

All that being said, I do want to use Observables as much as possible.  I will look into this more over the next several weeks.

As to the error you were working on, I fixed it. :-)

**Comment by sanbornsen** [comment]
I think we can close this issue.

**Comment by joshuawilson** [comment]
Agreed
