### ISSUE TITLE
Can we add id's to a workite,'s view and delete buttons?

### ISSUE THREAD

**Issue by ldimaggi** [almighty/almighty-ui#104]
Having the id's added to the workitem lists (http://localhost:8088/#/work-item-list) is a big help - thx!

Can we also add id's for the individual details and delete buttons? It;s not difficult to access the buttons relative to their parent's id's:

workItemList_ViewItemDetailBtn = .//*[@id='workItemList_OuterWrap_0']/div/div[1]/button[1]
workItemList_deleteListItemBtn = .//*[@id='workItemList_OuterWrap_0']/div/div[1]/button[2]

But - it would be much easier to access the buttons could be accessed directly through their id's - for example, by embedding the parent's id digit in the button id. Thx!

<div id="workItemList_OuterWrap_0" class="work-item-list-entry" _ngcontent-tsc-3="" ng-reflect-id="workItemList_OuterWrap_0">
  <div class="list-group-item" _ngcontent-tsc-3="">
    <div class="list-view-pf-actions" _ngcontent-tsc-3="">
      <button class="btn btn-default workItemList_ViewItemDetailBtn" _ngcontent-tsc-3="">View Details</button>
      <button class="btn btn-default delete-button workItemList_deleteListItemBtn" _ngcontent-tsc-3="">Delete</button>
        <div class="dropdown pull-right dropdown-kebab-pf" _ngcontent-tsc-3="">
        </div>
        <div class="list-view-pf-main-info" _ngcontent-tsc-3="">
  </div>
</div>

**Comment by joshuawilson** [comment]
We discussed this. The problem is that the button is on a repeating item and therefor it would be hard to give it a unique ID. We have talked about several ideas. The current idea was to give a descriptive Class that you could find within the ID. Please let me know if this works. I'm open to other options.

**Comment by ldimaggi** [comment]
Hey Josh - we can make it work as is - we can find the buttons by their class names relative to the unique work item element id's - for example:

The view button can be defined as:

  workItemViewButton:  {   
	  value: function (parentElement)         
	{ return parentElement.element(By.css( ".btn.btn-default.workItemList_ViewItemDetailBtn" )); }   
  },

And the button can be accessed by:

    page.workItemViewButton(page.firstWorkItem).getText().then(function (text) { 
    	console.log("text = " + text);
    });
    page.clickWorkItemViewButton(page.workItemViewButton(page.firstWorkItem));
