### ISSUE TITLE
Display the logged in user full name, image url (avatar) [Story #312 Visualizing the Login Status ]

### ISSUE THREAD

**Issue by nimishamukherjee** [almighty/almighty-ui#120]
https://github.com/almighty/almighty-core/issues/312

On the current application header, we can display the logged in user's:
- full name
- avatar

On a Git hub login, there are two parameters, we can get.

**Comment by joshuawilson** [comment]
Here is a reference to the UX for Login https://redhat.invisionapp.com/d/main#/console/8621915/185564523/preview

**Comment by nimishamukherjee** [comment]
PR #189 merged with master, hence closing the issue.
