### ISSUE TITLE
Login using Git Hub - Read/Write view management

### ISSUE THREAD

**Issue by nimishamukherjee** [almighty/almighty-ui#123]
https://github.com/almighty/almighty-core/issues/304

A user who has not logged in can:
- View the list of work items
- View a selected work item's details

A user who has logged in can:
- Quick add a work item
- Delete a work item
- Edit a work item's detail
- Can change the status of a work item

**Comment by sanbornsen** [comment]
- [ ] Restrict quick add a work item - https://github.com/almighty/almighty-ui/pull/164
- [ ] Restrict change work item status on list - https://github.com/almighty/almighty-ui/pull/164
- [ ] Restrict delete work item
- [ ] Restrict update work item on details page
