### ISSUE TITLE
Display and Update Work Item Details - Display confirmation dialog when navigating away without saving.

### ISSUE THREAD

**Issue by nimishamukherjee** [almighty/almighty-ui#126]
https://github.com/almighty/almighty-core/issues/298

If work item data has been changed but not saved, returning to the prior dialog requires confirmation.

Create a common shared component which
- takes input as title, text, array of buttons
- output would be an event (the parent needs to listen in on this)

**Comment by nimishamukherjee** [comment]
![confirm](https://cloud.githubusercontent.com/assets/1892722/19350830/f4ef454a-9176-11e6-8dcf-ae09559c66b6.png)

@mindreeper2420 / @Mgranfie need your input on task.

**Use case** : User is one the work item's details screen. He makes a few changes and clicks on "Back".
A confirmation dialogue box needs to show up stating that changes have been made which will be lost if the user navigates away.
Could you let us know the exact confirm behaviour?
We need a title, message, buttons, and what needs to happen on button clicks.

**Comment by mindreeper2420** [comment]
@nimishamukherjee how about this for the moda:

Text:
Do you want to discard your changes?

Buttons:
Cancel        Discard

**Comment by mindreeper2420** [comment]
@nimishamukherjee @joshuawilson just to note, this paradigm might change when the slide-out pane is implemented. We will need to revisit this action after that.

**Comment by nimishamukherjee** [comment]
Thanks @mindreeper2420 will implement this for now.
