### ISSUE TITLE
Display Work Item List - Deleting a WI needs confirmation

### ISSUE THREAD

**Issue by nimishamukherjee** [almighty/almighty-ui#127]
https://github.com/almighty/almighty-core/issues/297

From a list item, the user can delete a work item. Deleting a work item needs confirmation.

Reuse https://github.com/almighty/almighty-ui/issues/126

**Comment by michaelkleinhenz** [comment]
I just merged my listentry PR. I had to move the dialog from the list to the entry. That works and might be the right place, but in general, I would place the dialog on the topmost level, app.component.html/ts. That would ensure the dialog is truly generic and available everywhere.

**Comment by nimishamukherjee** [comment]
PR #152 merged with master, hence closing this task.
