### ISSUE TITLE
Display and Update Work Item Details [#298] - Implement the "Return to Previous" Function

### ISSUE THREAD

**Issue by michaelkleinhenz** [almighty/almighty-ui#129]
Userstory: https://github.com/almighty/almighty-core/issues/298

We need to figure out how the "Return" function will work. By clicking on a return function, the user should return to the previous view. For the detail view, this could be either the list view or another detail view.

As this function will be required for many other dialogs in the future, we have to figure out how to do this in a generic way.

In addition, this generic way should then be used for this specific dialog an be implemented.

**Comment by michaelkleinhenz** [comment]
Already properly implemented for the detail dialog. It uses the Angular 2 Location API. The browser back button also works as intended already. Documentation here: https://angular.io/docs/ts/latest/api/common/index/Location-class.html (see Location.back() behaviour).

**Comment by nimishamukherjee** [comment]
@michaelkleinhenz why did you close this issue and then re-open it? I think this can be closed. @joshuawilson your thoughts?

**Comment by michaelkleinhenz** [comment]
Yes, I was falling in the same thing Monica has fallen into: I hit the Close and Comment button instead of just Comment.
So basically: I think this is done and can be closed, but I don't just wanted to do it without you agreeing..

**Comment by nimishamukherjee** [comment]
We can close this. After the Detail's overlay code is merged, we will remain on the list view page. We would not have a return to previous scenario.
