### ISSUE TITLE
Create the Page Framework

### ISSUE THREAD

**Issue by michaelkleinhenz** [almighty/almighty-ui#130]
We need to create the responsive framework for the application/page that defines the breakpoints, implements the proper "frame" design etc. according to UX.

**Comment by nimishamukherjee** [comment]
@michaelkleinhenz, @SMahil : 
@mindreeper2420 has defined the breakpoints - https://github.com/almighty/almighty-ux/issues/1

**Comment by joshuawilson** [comment]
The original description is too vague for me. From one perspective we did this in the list view. From another it is talking about the Header and Footer and all within it.

**Comment by joshuawilson** [comment]
@michaelkleinhenz what are you looking for here?

**Comment by michaelkleinhenz** [comment]
I think we can close this now as this was done implicity in several other stories and is already done.
