### ISSUE TITLE
Setup codecov in almighty-ui repo

### ISSUE THREAD

**Issue by ppitonak** [almighty/almighty-ui#138]
Almighty-core repository have codecov.io setup so that it comments on pull requests (see e.g. https://github.com/almighty/almighty-core/pull/333#issuecomment-251288339). It would be nice to have the same in this repo.

**Comment by joshuawilson** [comment]
@kwk did you set this up for core?

**Comment by ppitonak** [comment]
Since https://github.com/almighty/almighty-core already uses Codecov.io, it should be relatively easy to setup. This is what needs to be done:

1. add `codecov` dev-dependency to `package.json`
2. create a new NPM script in `package.json` named e.g. "coverage:publish" and content `codecov`
3. publish code coverage results by adding `run run coverage:publish -- -t $VARIABLE_WITH_TOKEN` to `cico_build_deploy.sh` and `cico_run_tests.sh`
4. optionally, create a new file `.codecov.yml` or `codecov.yml` in project root or in directory `config` with configuration (e.g. see https://github.com/almighty/almighty-core/blob/master/.codecov.yml)
5. optionally, add codecov badge to the readme file

NOTE: 

- almighty-core specifies token directly in `cico_build_deploy.sh` and `cico_run_tests.sh` but IMHO it's not a correct way
- using env variable is not an option on public Jenkins due to security

@kwk are these instructions correct?
@kbsingh what is the safest way to set secret on ci.centos.org? ideally in such a way that it's available only to one particular job
