### ISSUE TITLE
User Angular2 forms for quick add work item

### ISSUE THREAD

**Issue by nimishamukherjee** [almighty/almighty-ui#139]
User Angular2 forms for quick add work item

**Comment by joshuawilson** [comment]
We have a commit for making the Details view use forms. Should the title of this issue be changed? Or was this PR applied to the wrong issue and we should leave it open?

**Comment by sanbornsen** [comment]
@nimishamukherjee is this done?

**Comment by nimishamukherjee** [comment]
Closing this task as converting the current form to Angular form does not add/enhance any value/benefit.
