### ISSUE TITLE
Make the list view responsive

### ISSUE THREAD

**Issue by nimishamukherjee** [almighty/almighty-ui#148]
Make the list view responsive

Wireframe:
Desktop - https://redhat.invisionapp.com/share/6A8T2M2XB#/screens/193330602
Mobile - https://redhat.invisionapp.com/share/KH8SMN9DN#/screens/192528686

**Comment by joshuawilson** [comment]
@SMahil was this resolved or is there still more work to do on it?

**Comment by SMahil** [comment]
@joshuawilson List view is responsive now. No more work on this issue
