### ISSUE TITLE
Sprint 121 task - implement UI test page object model

### ISSUE THREAD

**Issue by ldimaggi** [almighty/almighty-ui#151]
Build out preliminary test support following object page model () for:
- workitem list page in UI
- workitem board page in UI

Start building UI tests to support user stories - will be used as UI EE test.

See initial/partial implementation in: https://github.com/almighty/almighty-ui/pull/135

**Comment by joshuawilson** [comment]
@ldimaggi is there more to do on this?

**Comment by ldimaggi** [comment]
You read my mind - I think that we can close this for the current sprint. Need to update it when the UI changes. Thx!
