### ISSUE TITLE
Match UI To Existing Wireframes

### ISSUE THREAD

**Issue by mindreeper2420** [almighty/almighty-ui#158]
This bug list covers items in the UI that need to be updated to match the wireframes created by UXD. If an item/area has not been covered by wireframes, it should be run past UXD for review. All views should be created for mobile first, as the design process is mobile first.
- [x] Mobile First on all screens / interactions
- [x] Review visuals to match PatternFly
- [PatternFly Pattern Library](http://www.patternfly.org/pattern-library/#_) and [PatternFly Styles](http://www.patternfly.org/styles/#_)
- [x] Add Work Item needs to be fixed to the bottom of the screen
- [InVision Screen](https://redhat.invisionapp.com/share/798MZ3GG5#/185961156_AddAWorkItem-1-v3-)
- [GitHub Issue](https://github.com/almighty/almighty-ui/issues/149)
- [x] Desktop list view needs updating
- [InVision Screen](https://redhat.invisionapp.com/share/CJ8W68V2T#/193330603_List)
- [GitHub Issue](https://github.com/almighty/almighty-ui/issues/148)
- [x] Details View needs to be a panel
- [InVision Screen](https://redhat.invisionapp.com/share/UV8W6AEHX#/193330600_Panel_Edit)
- [GitHub Issue](https://github.com/almighty/almighty-ui/issues/168)
- [x] Username removed from navigation bar (there is no concept of a user ATM)
- [GitHub Issue](https://github.com/almighty/almighty-ui/issues/169)
- [x] Remove Status from List View
- [GitHub Issue](https://github.com/almighty/almighty-ui/issues/170)
- [x] Kabob Menu Implementation
- [InVision Screen - minimal kabob menu](https://redhat.invisionapp.com/share/YF8W6CC5Z)
- [InVision Screen - full kabob menu](https://redhat.invisionapp.com/share/YF8W6CC5Z#/screens/193140283)
- [GitHub Issue](https://github.com/almighty/almighty-ui/issues/171)
- [x] Button Alignments (bottom right, left to right: Cancel -> Save)
- [InVision Example](https://redhat.invisionapp.com/share/648W6CZVP#/194297190_ListView_-_6)
- [PatternFly Implementation](http://www.patternfly.org/pattern-library/forms-and-controls/conditional-fields/#/api)
- [GitHub Issue](https://github.com/almighty/almighty-ui/issues/172)
- [x] Proper Form layouts (according to PatternFly)
- [PatternFly Forms](http://www.patternfly.org/pattern-library/forms-and-controls/forms/#_)
- [GitHub Issue](https://github.com/almighty/almighty-ui/issues/174)
- [ ] Catalogue with UX team on @almighty-ux any issues that need review / questions on designs and patterns
- [Add Issues to this repo](https://github.com/almighty/almighty-ux/issues)

**Comment by joshuawilson** [comment]
@mindreeper2420 That is a great list. Can you please reference the existing issues for them or create an issue where one is missing. That will give us a place to discuss the design and track that it is getting worked.

**Comment by mindreeper2420** [comment]
@joshuawilson So individual issues for each on of these bullet points? I know one or two already exist, so I can link them here and create more, if that is the desire.

**Comment by mindreeper2420** [comment]
@joshuawilson I updated the list with proper references (GitHub, InVision and PatternFly) and created Issues in the almighty-ui repo.

**Comment by joshuawilson** [comment]
@mindreeper2420 thanks, that will help us track the issues and get them worked. :)

**Comment by nimishamukherjee** [comment]
Closing as the list has been completed.
