### ISSUE TITLE
Create Panel for Details Desktop View

### ISSUE THREAD

**Issue by mindreeper2420** [almighty/almighty-ui#168]
The Work Item Details view should be in a panel that slides out from the right side of the screen (desktop), rather than it's own page (mobile).

See InVision Prototype for details: https://redhat.invisionapp.com/share/UV8W6AEHX#/screens/193330600_Panel_Edit

**Comment by SMahil** [comment]
@mindreeper2420 How much width we are targeting for panel? And How it should come from 768px to 992px?

**Comment by mindreeper2420** [comment]
@smahil @joshua it should take about about 1/3 of the screen on desktop views. There are no defined pixel widths at the moment. If you'd like, I can review on a branch, once you have a rough stage of it.

**Comment by nimishamukherjee** [comment]
PR #263 merged with master hence closing this task.
