### ISSUE TITLE
Remove Username from Navigation Bar

### ISSUE THREAD

**Issue by mindreeper2420** [almighty/almighty-ui#169]
As there is currently no concept of a User, there should not be a username placeholder or dropdown in the navigation bar. The navigation bar should only show the product name.

**Comment by joshuawilson** [comment]
If there is no User, what are we doing with the Login?

**Comment by nimishamukherjee** [comment]
@mindreeper2420 we have enabled user login via GitHub. We now display the Git Hub username and avatar.
Can you confirm if this is fine?

**Comment by mindreeper2420** [comment]
@joshuawilson @nimishamukherjee just test on the site and it looks good. I'm good with closing this issue.

**Comment by nimishamukherjee** [comment]
PR #189 merged with master hence closing this issue.
