### ISSUE TITLE
Move Status Position in List View

### ISSUE THREAD

**Issue by mindreeper2420** [almighty/almighty-ui#170]
According to the List View prototypes, there is no indication of Work Item status. As such, that should be removed from the existing UI until there is a visual for that module.

InVision Prototype: https://redhat.invisionapp.com/share/CJ8W68V2T#/193330603_List

**Comment by SMahil** [comment]
@mindreeper2420 As per our last discussion, We need to show the Work Item Status. Can you please confirm the change and provide me the icon names(for mobile view)

**Comment by mindreeper2420** [comment]
@SMahil here is a view with the Work Item Status: https://redhat.invisionapp.com/share/GZ8Y29LJ5#/183714502_ALM_Basic_Workflow_24Aug3-pdf_7

The icons are:
- New: fa-circle-thin
- In Progress: fa-adjust
- Resolved: pficon-resources-full
- Closed: fa-check-circle

The status can also appear in the mobile view, in the same place as desktop.

**Comment by joshuawilson** [comment]
@mindreeper2420 can the status be changed by clicking on the icon?

**Comment by mindreeper2420** [comment]
@joshuawilson Not in this version, as it has not been laid out in the mobile ui yet (using native controls, etc.). To change the status, the user (currently) has to open up the panel and change it via the dropdown button (just like what is currently in the list view).

If this turns out to be too awkward or doesn't flow correctly, we're open for adjustment in the next pass. I'll post this question in the UXD standup tomorrow AM.

**Comment by mindreeper2420** [comment]
@joshuawilson @SMahil Here is Brian's visual, which shows the status icon information and layouts:
- [Almighty-UX](https://github.com/almighty/almighty-ux/issues/36)
- [InVision Prototype](https://redhat.invisionapp.com/share/NU8YPHLJP#/screens/196006933)

@bdellasc - can you comment on anything that may need your review?

**Comment by nimishamukherjee** [comment]
PR #216 merged with master. Hence closing this bug.
