### ISSUE TITLE
Kabob Menu Implementation

### ISSUE THREAD

**Issue by mindreeper2420** [almighty/almighty-ui#171]
According to the prototypes, the Kabob menu (the vertical ellipsis icon) controls the actions of the Work Item. These include moving the order of the item (to the top or bottom), Opening the item and deleting the item.
- Delete and View Details buttons should be removed from the list view.
- Opening an action from the Kabob that opens a modal (such as delete) should close the Kabob so that it is not still open.

InVision Prototype: https://redhat.invisionapp.com/share/YF8W6CC5Z#/screens/193140283

PatternFly: http://www.patternfly.org/pattern-library/widgets/#kebabs

**Comment by sanbornsen** [comment]
Each action specified in the design is a task. I assume this issue is more about get the kebob menu in place and get it working properly. Am I right?

**Comment by sanbornsen** [comment]
This issue is not one task, if I break it - 
- [ ]  Delete and View details button should be removed. (How to access the details page?)
- [ ]  Opening an action modal should close the kebob.
- [ ]  Move item top or bottom actions in the kebob (Need back-end support on this)

**Comment by mindreeper2420** [comment]
@sanbornsen Accessing the Details page is done either by the 'Open' option in the kabob, or my clicking on the row itself (other areas reference showing the panel. There is not a separate details page).

**Comment by joshuawilson** [comment]
@sanbornsen you can still implement moving items up and down with the kabob, you just can't persist the location. We do not have ordering setup yet.

**Comment by sanbornsen** [comment]
@joshuawilson @mindreeper2420 I'd rather wait for the backend instead. Because anyway if we don't save the order, adding a new item will again re order it.

**Comment by sanbornsen** [comment]
Last PR regarding this is merged - https://github.com/almighty/almighty-ui/pull/324
Hence closing the issue.
