### ISSUE TITLE
Consistent Button Alignment

### ISSUE THREAD

**Issue by mindreeper2420** [almighty/almighty-ui#172]
As a user, I want to be able to consistently and easily locate the various buttons that pertain to my inputs.

Criteria:
- Buttons follow [PatternFly formatting](http://www.patternfly.org/pattern-library/forms-and-controls/conditional-fields/#/api)
- [Buttons and Buttons Group in PatternFly](http://www.patternfly.org/pattern-library/widgets/#buttons)
- Keyboard inputs (Enter and Esc) are accepted

**Comment by nimishamukherjee** [comment]
PR #263 merged to master. Quick Add, List View, and Details View updated as per visual design.
@mindreeper2420 can we close this?

**Comment by mindreeper2420** [comment]
If PR was approved and merged, I see no reason not to close. Thank you for adding the PR# to the story.

**Comment by joshuawilson** [comment]
PR was merged, so I'm closing this.
