### ISSUE TITLE
Form Layout and Consistency

### ISSUE THREAD

**Issue by mindreeper2420** [almighty/almighty-ui#174]
Based off of the current detail page, the form inputs and selectors are inconsistent in their styling and do not match PatternFly's methods (vs Bootstrap defaults).
- Squared corners
- Selector styling
- Text Box sizing

http://www.patternfly.org/pattern-library/forms-and-controls/forms/#_

**Comment by nimishamukherjee** [comment]
PR #263 merged to master. Quick Add, List View, and Details View updated as per visual design.
@mindreeper2420  can we close this?
