### ISSUE TITLE
View details button not working on Firefox

### ISSUE THREAD

**Issue by nimishamukherjee** [almighty/almighty-ui#177]
Browser - Firefox
On the work items list view, the view details button is not working.

**Comment by naina-verma** [comment]
@nimishamukherjee , For me its not working on chrome too

**Comment by naina-verma** [comment]
@nimishamukherjee ,
console error in firefox browser : https://gist.github.com/naina-verma/03d5900f357fcbfb019848f2c6587b23

**Comment by sanbornsen** [comment]
The fix is in PR - https://github.com/almighty/almighty-ui/pull/187

**Comment by nimishamukherjee** [comment]
PR #187 merged, hence closing the bug
