### ISSUE TITLE
ALM UI should allow desktop users to "just type"

### ISSUE THREAD

**Issue by ldimaggi** [almighty/almighty-ui#195]
The ALM UI should allow users to "just type" to create a new workitem. They should not have to press any buttons before typing in a new work item title.

![1](https://cloud.githubusercontent.com/assets/642621/19453164/1138ce2a-9482-11e6-96e1-d475ad8f1768.png)
![2](https://cloud.githubusercontent.com/assets/642621/19453163/11348d42-9482-11e6-9c1c-72f7a666a181.png)

**Comment by mindreeper2420** [comment]
@ldimaggi Is this something you are considering as a bug? If so, it should be filed under Almighty UX issues. The UX design for this does not auto-focus on the field when the page is loaded.

@SMahil @joshuawilson @Mgranfie

**Comment by nimishamukherjee** [comment]
@ldimaggi could you check @mindreeper2420 's comment?

**Comment by ldimaggi** [comment]
This is now working in the UI - closing - thx!
