### ISSUE TITLE
ALM UI should allow desktop cancel a new work item

### ISSUE THREAD

**Issue by ldimaggi** [almighty/almighty-ui#196]
See attached desktop screenshots - the user, once he/she selects to create a new workitem - does not have a way to cancel that new workitem.

![1](https://cloud.githubusercontent.com/assets/642621/19453319/c7177098-9482-11e6-8409-652035963f25.png)
![2](https://cloud.githubusercontent.com/assets/642621/19453320/c71a865c-9482-11e6-8a15-00d1e705d5d4.png)

**Comment by mindreeper2420** [comment]
@joshuawilson the UX for this item is covered under [almighty-ux#36](https://github.com/almighty/almighty-ux/issues/36) and [InVision Prototype](https://redhat.invisionapp.com/share/NU8YPHLJP#/screens/195933689)

**Comment by joshuawilson** [comment]
There is now an X that closes it. 
Closing.
