### ISSUE TITLE
Can't Open Work Items from Mobile

### ISSUE THREAD

**Issue by mindreeper2420** [almighty/almighty-ui#197]
As a mobile user, I cannot do anything with the work items, other than delete them. This differs from the desktop where I can view details and, from there, make additional changes that are then reflected in the List View of the work item.

**Comment by nimishamukherjee** [comment]
@mindreeper2420 based on https://redhat.invisionapp.com/share/KY8LXF5QV#/screens/184288852
the View Details button is not visible on a mobile.

How do navigate to the details view on the Mobile?

We would have in-line editing (https://redhat.invisionapp.com/share/KH8SMN9DN#/screens) so we cannot click on the row.

Do we make 'View Details' a part of the Kabob menu on the mobile?

**Comment by mindreeper2420** [comment]
@nimishamukherjee A few things:

1) There is actually no 'View Details' button on desktop (or any view). That button needs to be removed from the desktop view. See the [Desktop Visuals](https://redhat.invisionapp.com/share/BC8ZQ12MF#/197105081_A-0100-Create_Work_Item) for this information.

2) The mobile link you shared is outdated. This is the correct one to use: [ALM_SaveNew&Changes_MB](https://redhat.invisionapp.com/share/V78XEZ032#/193131363_ListView_-_3).

This also covers the question on the Kabob menu usage - touching the kabob menu will open up a menu where 'Open' is an option. Touching the Title will enable inline editing.


This product is mobile first, so it MUST to work on mobile. If there are questions during the development process that prevent it from working on mobile, please submit an Issue on almighty-ux.

**Comment by sanbornsen** [comment]
This issue is solved in PR - https://github.com/almighty/almighty-ui/pull/265
Hence closing it.
