### ISSUE TITLE
Cannot Add Items to List in Mobile View

### ISSUE THREAD

**Issue by mindreeper2420** [almighty/almighty-ui#203]
When attempting to add a new Work Item to the list on mobile, the input field is blocked by the keyboard. The input does not stay fixed to the top of the keyboard once a user touches the Title input. This did not occur before the Add Work Item inputs were moved to the bottom of the screen.

![img_0065](https://cloud.githubusercontent.com/assets/4032718/19500310/e3b09fda-9569-11e6-96e3-ce8b70a30e11.png)

**Comment by mindreeper2420** [comment]
@Mgranfie adding you as a participant.

**Comment by SMahil** [comment]
@mindreeper2420 Can you specify on which mobile and browser you find this issue

**Comment by mindreeper2420** [comment]
This was done on iOS 10, iPhone 6s Plus using Chrome.

**Comment by nimishamukherjee** [comment]
PR #219 merged with master, hence closing the bug.
