### ISSUE TITLE
Add A Work Item Text Does Not Match UX

### ISSUE THREAD

**Issue by mindreeper2420** [almighty/almighty-ui#204]
The text for 'Add A Work Item' is incorrect and does not match the UX. "Work Item" is two words and needs to be written as such.

- [UX Design](https://redhat.invisionapp.com/share/S2902RXE5#/192528688_ListView_-_1)

![img_0066](https://cloud.githubusercontent.com/assets/4032718/19500427/12c6fb1a-956b-11e6-86e8-0c026e7ed086.png)

![screen shot 2016-10-18 at 7 43 05 pm](https://cloud.githubusercontent.com/assets/4032718/19500429/1d670092-956b-11e6-927e-e13bf8c3a1f1.png)

**Comment by mindreeper2420** [comment]
@Mgranfie adding you as a participant.

**Comment by nimishamukherjee** [comment]
PR #218 merged with master, hence closing this bug.
