### ISSUE TITLE
Second Level Navigation Should Be Hidden/Removed

### ISSUE THREAD

**Issue by mindreeper2420** [almighty/almighty-ui#205]
According to the UX designs, there is not a second level navigation. The UI, in it's current state, has "Work Item List" and "Board" as navigation options. These should be either hidden from view or removed.

### [UX Visuals](https://redhat.invisionapp.com/share/ZU902Z1WQ#/195933776_A-0400)

----
### Current demo.almighty.io UI
![screen shot 2016-10-18 at 7 43 05 pm](https://cloud.githubusercontent.com/assets/4032718/19500767/4798ff34-956e-11e6-8b3b-20cef128a2b8.png)

**Comment by mindreeper2420** [comment]
@Mgranfie adding you as a participant.

**Comment by nimishamukherjee** [comment]
PR #217 merged with master. Hence closing this bug.
