### ISSUE TITLE
Work Item Linking - UI for creating a work item link

### ISSUE THREAD

**Issue by nimishamukherjee** [almighty/almighty-ui#207]
Reference Story - https://github.com/almighty/almighty-core/issues/306

Develop the UI for work item linking based on https://redhat.invisionapp.com/share/J38SPOKNA#/screens

**Comment by joshuawilson** [comment]
@harrybabu should this be assigned to your or is someone else doing this?

**Comment by harrybabu** [comment]
Done. As the code got pushed to master
