### ISSUE TITLE
Realize UX for Work Item Detail View

### ISSUE THREAD

**Issue by nimishamukherjee** [almighty/almighty-ui#208]
Will refer to https://redhat.invisionapp.com/share/NU8YPHLJP#/screens/196006936

**Comment by nimishamukherjee** [comment]
@joshuawilson, @SMahil initials thoughts on having the view details and work item list of the same page as per the wirefram
1. We need a work-item-home
2. Work item home will load work item list and work item detail

Is this the right approach?

**Comment by sanbornsen** [comment]
* Can the user click on items under the layover?
* Will clicking out of the layover closes the layover?
* Can we change the details URL and make something under work-item-list/ ?

**Comment by mindreeper2420** [comment]
@sanbornsen @michaelkleinhenz @joshuawilson 
* Clicking on the rows behind the slide-out panel will change the details inside of the panel. This will allow for easy switching between item details.
* There should be an 'X' in the upper right of the panel to close the panel?

**Comment by sanbornsen** [comment]
This done and merged with master.
