### ISSUE TITLE
Implement unit tests for change on logout in each component or subcomponent.

### ISSUE THREAD

**Issue by sanbornsen** [almighty/almighty-ui#210]

**Comment by joshuawilson** [comment]
@sanbornsen is this something you plan to work on? Considering we closed the login/logout user stories.

**Comment by nimishamukherjee** [comment]
@joshuawilson this has been done for the details page

**Comment by sanbornsen** [comment]
@joshuawilson I don't think I can take it up for the sprint.

**Comment by joshuawilson** [comment]
@nimishamukherjee which PR has this in it?

**Comment by nimishamukherjee** [comment]
@joshuawilson PR #263 takes care of logged in and logged unit tests.

**Comment by nimishamukherjee** [comment]
PR #263 merged. The details view contains unit tests which check for logged in and logged out scenario.
