### ISSUE TITLE
Description Needs to be Part of 'Quick Add'

### ISSUE THREAD

**Issue by mindreeper2420** [almighty/almighty-ui#211]
As part of the 'Quick Add' functionality, the user should be able to add a description. This is not a required field.

[Visual Design](https://redhat.invisionapp.com/share/NU8YPHLJP#/screens/197122698)

**Comment by SMahil** [comment]
@mindreeper2420 Can you provide the mobile design for same

**Comment by mindreeper2420** [comment]
@smahil the mobile view does not have the description field due to spacing and usability restrictions. Future iterations will look at mid-tier screens that will have more room.

**Comment by sanbornsen** [comment]
Can we close this issue?

**Comment by mindreeper2420** [comment]
@sanbornsen If fixed, I'd attach the PR that fixes this bug, and then I'd be fine with closing it. @michaelkleinhenz @joshuawilson is this a good method for verifying bugs? Attaching the merged PR?

**Comment by joshuawilson** [comment]
@mindreeper2420 I agree.

Fixed in #253
