### ISSUE TITLE
"Change State" on a workitem at http://demo.almighty.io/ raises an exception

### ISSUE THREAD

**Issue by ldimaggi** [almighty/almighty-ui#212]
See screenshot:

![exception](https://cloud.githubusercontent.com/assets/642621/19532380/790b4aae-9609-11e6-9a8c-629f78090585.png)

**Comment by sanbornsen** [comment]
I don't think this is how we are going to change the sate.

**Comment by mindreeper2420** [comment]
@sanbornsen @ldimaggi This will be the first iteration for changing state on mobile, but it should not be in a popover menu such as this. Refer to [this screen](https://redhat.invisionapp.com/share/TE90YWM4J#/194297166_KabobMenu) for how the menu should open (Change State is not in this reference, just demonstrating how the menu should appear on mobile).

**Comment by sanbornsen** [comment]
@mindreeper2420 about that, we need to discuss. The design you have shown is a native design for iOs and Android has something similar, but that works only if we use <select><option /></select> in HTML. I guess in order to implement that in our current system we need a work around. @joshuawilson @SMahil please comment.

**Comment by mindreeper2420** [comment]
@sanbornsen @joshuawilson @SMahil How is the current system not HTML? I would think that a slide-up modal from the bottom would be a CSS/SASS styled <div> with hide/show and animation characteristics?

**Comment by joshuawilson** [comment]
The Status should not be changed in the listview. Closing.

**Comment by joshuawilson** [comment]
Sorry for closing. After a more careful reading of the comments, this is not decided.

**Comment by sanbornsen** [comment]
@mindreeper2420 Well, that design you have provided is a native design for iOs for select HTML tag. Do you want us to replicate that design for our application with Angular and  HTML CSS?

**Comment by joshuawilson** [comment]
@sanbornsen that would make for an interesting component. A dropdown menu with side pop-outs. I would maybe save this to the next sprint.

**Comment by joshuawilson** [comment]
@sanbornsen @mindreeper2420  what is the status of this?

**Comment by mindreeper2420** [comment]
@joshuawilson not sure what I can do in regards to this particular issue, as it relates to an error in the code. If design can't be matched, might be better to open a separate issue.

**Comment by sanbornsen** [comment]
@mindreeper2420 @joshuawilson there are three options for this issue: 

1. Fix the console error (Code change only)
2. Remove the "Change state" item from the list.
3. Complete "Change state" work flow. (We'd need the UX specification for that)

**Comment by mindreeper2420** [comment]
@sanbornsen @joshuawilson - from a UX POV, there are no workflows for changing the state in the list view.

**Comment by joshuawilson** [comment]
So the solution is simple then, remove it from the menu.

**Comment by sanbornsen** [comment]
Cool !! I am on it.
