### ISSUE TITLE
Status Indicator is Incorrect and Incorrectly Positioned

### ISSUE THREAD

**Issue by mindreeper2420** [almighty/almighty-ui#224]
> (As of October 21, 2016 @ 11:15am EDT)

The status indicator should be an icon and positioned on the left side of the list item - based off of this [Design](https://redhat.invisionapp.com/share/BH91MDY82#/196310339_A-0100-Visuals).

Currently, the demo.almighty.io site has it as a button, positioned on the right.
<img width="1918" alt="screen shot 2016-10-21 at 11 15 33 am" src="https://cloud.githubusercontent.com/assets/4032718/19603660/f048c066-977f-11e6-894c-fb6aa44e533b.png">

**Comment by joshuawilson** [comment]
@mindreeper2420 Thanks for the link to the new wireframe. Changing to an icon will take a bit more work, but you had said to move it to the right side when we asked the first time. That is why it was moved.

@SMahil Can you please move it back to the left.

**Comment by sanbornsen** [comment]
@mindreeper2420 
- How shall we change the status or type on workitem list? Any design for that?
- There are more than three status and types, how do we go about them?

**Comment by nimishamukherjee** [comment]
@mindreeper2420 / @joshuawilson the status icons and type icons are not intuitive. What additional information can we provide around the icons to make it easier for the user to understand.

**Comment by mindreeper2420** [comment]
@sanbornsen - the design (this iteration) does not call for changing the status in the list. That is done in the detail view. Match the design for now and updates will follow. Might be helpful to create a bug in almighty-ux.

Please reach out to Brian for information on additional icons.

**Comment by mindreeper2420** [comment]
@nimishamukherjee @joshuawilson - if not in this iteration of the design (or in PatternFly), then there is nothing additional to add for showing more information. Please reach out to Brian by filing a bug on almighty-ux requesting this information.

**Comment by mindreeper2420** [comment]
Yeah, that was before the final visuals came out.

**Comment by sanbornsen** [comment]
@SMahil can we have a HTML CSS for it? I can work on the component.

**Comment by SMahil** [comment]
@sanbornsen Please find the HTML at below branch:

almighty-ui-224

**Comment by nimishamukherjee** [comment]
PR #263 merged to master. Status indicator position updated.
@mindreeper2420 can we close this?
