### ISSUE TITLE
Quick workitem add is displayed on bottom of screen for Firefox 38.4.0, not for Chrome 50.0.2661.86

### ISSUE THREAD

**Issue by ldimaggi** [almighty/almighty-ui#225]
See attached screenshot - this is after building from master on October 21

![chrome_firefox](https://cloud.githubusercontent.com/assets/642621/19605577/22f07abe-9789-11e6-97c8-7a839f8b7810.png)

**Comment by joshuawilson** [comment]
@ldimaggi it appears that you are not logged in. The Quick Add and several other "edit' features are not available while logged out. If you agree, please close the issue.

**Comment by joshuawilson** [comment]
@ldimaggi can you please confirm this?

**Comment by joshuawilson** [comment]
Works as expected, just needed to login.
