### ISSUE TITLE
No login available on mobile

### ISSUE THREAD

**Issue by mindreeper2420** [almighty/almighty-ui#227]
The option to log into the system is not available on mobile devices. The hamburger menu does not open when touched. As such, work items cannot be added to the list.

**Comment by joshuawilson** [comment]
@SMahil Can you please take a look at this?

**Comment by sanbornsen** [comment]
@mindreeper2420 
We tried to follow the design on pattern-fly - http://www.patternfly.org/pattern-library/navigation/vertical-navigation/vertical-navigation.html#_

The mobile view of it has not login button. Keeping in mind we need to have that feature, do you have a UX ready for that? My suggestion would be, putting it into a vertical navigation (yet to implement) which will come out clicking on the humburger as the example URL.

**Comment by sanbornsen** [comment]
I see a small user icon in this layout - https://redhat.invisionapp.com/share/798MZ3GG5#/185961156_AddAWorkItem-1-v3-

**Comment by sanbornsen** [comment]
I followed the link on previous comment and added this PR - https://github.com/almighty/almighty-ui/pull/229

@joshuawilson @nimishamukherjee @SMahil @mindreeper2420 Please review !!
