### ISSUE TITLE
Username not displayed after login

### ISSUE THREAD

**Issue by naina-verma** [almighty/almighty-ui#228]
Username not displayed after login , if there is no fullName defined in your github profile
I have tried Login on Firefox and chrom (Incognito also).  The Username is not displayed on desktop browsers.
Steps to reproduce 
- clear browser cache 
- Get request demo.almighty.io 
-  Login using github account 
  Results : Avatar with logout is visible but username is not 
  Getting console output
  GET Call for User :  Request URL:http://demo.api.almighty.io/api/user
  Response : {"fullName":"","imageURL":"https://avatars.githubusercontent.com/u/19172870?v=3"}
  If fullName is null we must display github display name .
  ![screenshot from 2016-10-24 14-34-45](https://cloud.githubusercontent.com/assets/19172870/19640060/b9bfcf8c-99f8-11e6-8b68-ea3ec8114e75.png)
  ![screenshot from 2016-10-24 14-40-31](https://cloud.githubusercontent.com/assets/19172870/19640061/b9ca7b9e-99f8-11e6-8955-e797ec2f7cf7.png)
  ![screenshot from 2016-10-24 14-46-37](https://cloud.githubusercontent.com/assets/19172870/19640062/b9d6fc66-99f8-11e6-90fa-6f1c41a7866a.png)
  ![screenshot from 2016-10-24 14-46-43](https://cloud.githubusercontent.com/assets/19172870/19640063/b9f0a01c-99f8-11e6-8a86-91354a6501d7.png)

**Comment by naina-verma** [comment]
Tried Few more things
- Added Profile name to Github account ,logout(from almighty ui and github)
- Revoke authorization of almighty and clear cache, login again

**Comment by aslakknutsen** [comment]
Core currently only fetch the 'User' data from GitHub on the first login/when the account is created.

We can't guarantee that FullName will be set as this is coming from remote system which doesn't have this as a requirement, but we could re-fetch data from GitHub on each login and update the remote info if needed. That would at least catch the 'i've added my full name later' use case.

**Comment by joshuawilson** [comment]
@aslakknutsen are you taking this as a Core task?
@naina-verma can we close this issue?

**Comment by naina-verma** [comment]
@joshuawilson , yes i have created the bug in core , you can close this issue.
Thanks
