### ISSUE TITLE
Use ng2-dropdown directive library instead of in dwopdown component for dropdown.

### ISSUE THREAD

**Issue by sanbornsen** [almighty/almighty-ui#234]

**Comment by ppitonak** [comment]
@sanbornsen is it this library https://github.com/pleerock/ng2-dropdown ? It specifies license (MIT) only in package.json so we should find out if that is sufficient.

**Comment by joshuawilson** [comment]
@ppitonak that is a good point, I'll ask Richard.

**Comment by sanbornsen** [comment]
@ppitonak Sorry !! i missed that. Looks like @joshuawilson go it covered.
