### ISSUE TITLE
404 on font resources on demo.almighty.io

### ISSUE THREAD

**Issue by aslakknutsen** [almighty/almighty-ui#237]
Currently, the following resources return 404:

http://demo.almighty.io/node_modules/patternfly/dist/fonts/PatternFlyIcons-webfont.ttf
http://demo.almighty.io/node_modules/patternfly/dist/fonts/PatternFlyIcons-webfont.woff

**Comment by joshuawilson** [comment]
@SMahil can you look into this please.

**Comment by ppitonak** [comment]
It seems that you need to be logged-in to reproduce.
