### ISSUE TITLE
Mobile (Phone) First - List View

### ISSUE THREAD

**Issue by mindreeper2420** [almighty/almighty-ui#24]
As a user, I want to be able to view the items in my list on my mobile (phone type TBD) device, so that I can see all the issues that exist, for the MVP, while away from my laptop. This view will need to progressively scale up to a tablet and then desktop device (separate stories to follow).

Reference:

https://redhat.invisionapp.com/share/KY8LXF5QV

InVision Prototype:
* ~~https://redhat.invisionapp.com/share/XB8HFYE6J~~
* https://redhat.invisionapp.com/share/798MZ3GG5#/185961156_AddAWorkItem-1-v3-

**Comment by SMahil** [comment]
@mindreeper2420 Please provide the access for invisionapp designs

**Comment by mindreeper2420** [comment]
@SMahil the link has been updated, but the design is not finalized.

**Comment by joshuawilson** [comment]
The designs are the target for Sprint #120

**Comment by mindreeper2420** [comment]
![screen shot 2016-09-07 at 9 36 04 am](https://cloud.githubusercontent.com/assets/4032718/18313905/d507e458-74de-11e6-868f-7394f9f4e600.png)

**Comment by michaelkleinhenz** [comment]
@mindreeper2420 is the ux task done with the mockup?

**Comment by mindreeper2420** [comment]
@michaelkleinhenz not at this time. The current sprint ends on Sept 13, so it should be marked as closed by then. I'll update this once the item has been closed on the UX side. This is the same for issue #25

**Comment by mindreeper2420** [comment]
@joshuawilson The initial design phase is complete and can be found under almighty/almighty-ux#5
