### ISSUE TITLE
We we retain the state button in the workitem list view and the change state option in each workitem's kebab UI element too?

### ISSUE THREAD

**Issue by ldimaggi** [almighty/almighty-ui#244]
See attached screenshot - will we retain both of these?

![screenshot from 2016-10-26 14-53-59](https://cloud.githubusercontent.com/assets/642621/19740554/10bc0310-9b8d-11e6-9719-d26445e2e505.png)

**Comment by mindreeper2420** [comment]
@ldimaggi the State Change button (Open w/dropdown) should not be in the UI. According to the wireframes, it should only be a status icon, located on the left of the screen. @Mgranfie

**Comment by nimishamukherjee** [comment]
The UI has been updated. State icon is an icon on the left of the title.
