### ISSUE TITLE
Mobile (Phone) First - Add A New Work Item

### ISSUE THREAD

**Issue by mindreeper2420** [almighty/almighty-ui#25]
As a user, I want to be able to add a new item (quickly) to the list view, so that I can quickly add, one or more work items to the list, while not on my laptop. This needs to follow the mockups in the InVision prototype linked below, as well as the PDD (finalization to come).

* Initial InVision Prototype:
https://redhat.invisionapp.com/share/K28FKIFTE#/184725156_AddAWorkItem-1-iPhone_5-

Once the design is finalized, this Issue will be updated.

**Comment by joshuawilson** [comment]
The designs are the target for Sprint #120

**Comment by mindreeper2420** [comment]
@joshuawilson This item has been completed for design and can be found under almighty/almighty-ux#4
