### ISSUE TITLE
Incorrect Quick Add Behavior

### ISSUE THREAD

**Issue by mindreeper2420** [almighty/almighty-ui#259]
As a user, I expect the action of hitting 'Enter' to quickly add an item to the list to be usable whether I am entering information in the Title or Description fields.

Problem:
- The current iteration only adds an item using the Enter key while active in the Title input
- Hitting Enter in the Description fields adds a new line

Solution:
- A user can hit Enter while either the Title or Description is active in order to quickly add a new item
- Shift + Enter should be used for adding a new line to the Description field
- The Description field should not have the 'drag to expand' capability - it should expand on its own as required by the amount of text entered

**Comment by aslakknutsen** [comment]
> Hitting Enter in the Description fields adds a new line

Return focus to Title when Enter is hit?

> The Description field should not have the 'drag to expand' capability - it should expand on its own as required by the amount of text entered

Also 'scale back down' after Enter is hit. ?

**Comment by sanbornsen** [comment]
- [ ] Enter in description field should save the new work item. 
- [ ] Shift + Enter should create a new line.
- [ ] Return focus to title on hit Enter.
- [ ] Description field should auto increase the height.

**Comment by sanbornsen** [comment]
It's done.
