### ISSUE TITLE
Quick add description text box not align wrt to title box

### ISSUE THREAD

**Issue by naina-verma** [almighty/almighty-ui#261]
Quick add description text box not align wrt to title box
There is slight modification  required in description text box alignment. 
Its height should be equal to title txt box.
It happened in only firefox browser (Chrome is working fine)
![screenshot from 2016-11-02 12-39-16](https://cloud.githubusercontent.com/assets/19172870/19919611/f24a79e4-a0f9-11e6-80f9-d6b2b73ad11f.png)

**Comment by SMahil** [comment]
@naina-verma this issue is already fixed. Please find the screenshot
<img width="1409" alt="screen shot 2016-11-07 at 1 49 43 pm" src="https://cloud.githubusercontent.com/assets/10396359/20050782/247c318c-a4f1-11e6-93e9-41b3596cda54.png">

**Comment by naina-verma** [comment]
@SMahil ,This shows up on firefox version 47.0
![screenshot from 2016-11-07 14-36-13](https://cloud.githubusercontent.com/assets/19172870/20051955/aaee819c-a4f7-11e6-8817-7bbda5fcd66f.png)

**Comment by sanbornsen** [comment]
@SMahil @naina-verma Is it done?

**Comment by naina-verma** [comment]
@sanbornsen , @SMahil is working on it ,not done yet!

**Comment by nimishamukherjee** [comment]
@naina-verma can you verify this.

**Comment by naina-verma** [comment]
@SMahil ,LGTM
Verified on Firefox and Chrome !

**Comment by sanbornsen** [comment]
Wasn't it solved long time back?

**Comment by nimishamukherjee** [comment]
Thanks @naina-verma . Closing this issue as PR #322 merged.

**Comment by nimishamukherjee** [comment]
PR #323 merged. Hence closing this issue.
