### ISSUE TITLE
Inconsistent display of save/cancel buttons in work item detail display

### ISSUE THREAD

**Issue by ldimaggi** [almighty/almighty-ui#268]
Can we change the order (left/right) of the buttons consistent? See attached screenshot.
![inconsistentorder](https://cloud.githubusercontent.com/assets/642621/20035230/6afc8c78-a3b2-11e6-9dc1-15390ea35b9c.png)

**Comment by sanbornsen** [comment]
@nimishamukherjee has done it. It's on the PR. SO we can close it.
