### ISSUE TITLE
Feature request - can we add id's to work item detail page elements?

### ISSUE THREAD

**Issue by ldimaggi** [almighty/almighty-ui#269]
Detail Page. Work Item Title Edit Save Button:
<div id="workItemTitle_btn_save" class="fl btn-small detail-action-btn" _ngcontent-dwu-8="" ng-reflect-klass="fl btn-small detail-action-btn" ng-reflect-ng-class="[object Object]">
<span class="fa fa-check" _ngcontent-dwu-8=""/>
</div>

Detail Page. Work Item Title Edit Cancel Button:
<div class="fl btn-small detail-action-btn" _ngcontent-dwu-8="">
<span class="fa fa-close" _ngcontent-dwu-8=""/>
</div>

------> Can we add an id to the Cancel Button?

=====================================================================

Detail Page. Work Item Description Edit Save Button:

<div class="fl btn-small pull-right detail-action-btn" _ngcontent-plw-8="">
<span class="fa fa-check" _ngcontent-plw-8=""/>
</div>

Detail Page. Work Item Description Edit Cancel Button:
<div class="fl btn-small pull-right detail-action-btn" _ngcontent-plw-8="">
<span class="fa fa-close" _ngcontent-plw-8=""/>
</div>

------> Can we add id's to these Buttons?

**Comment by nimishamukherjee** [comment]
The following have IDs on the View Details panel:
- Title edit span
- Edit Save div
- Edit Cancel div
- Description edit icon span
- Description Save div
- Description Cancel div

https://github.com/almighty/almighty-ui/commit/9d41ec7224ba9fddad4b1dbe7289b6cd4a14e87f

**Comment by sanbornsen** [comment]
So, we got it covered too !!
