### ISSUE TITLE
In the work item page, can we move the description edit icon/button to be outside of the text box?

### ISSUE THREAD

**Issue by ldimaggi** [almighty/almighty-ui#270]
See attached screenshot - thx!

![screenshot from 2016-11-05 23-52-55](https://cloud.githubusercontent.com/assets/642621/20035252/58120fba-a3b3-11e6-8174-184f77803442.png)

**Comment by mindreeper2420** [comment]
@ldimaggi @nimishamukherjee this is more of a request for UX, as this matches the visual design shown in this design: https://invis.io/NU8YPHLJP

**Comment by sanbornsen** [comment]
We have implemented it as per the design. Closing the issue !!
