### ISSUE TITLE
View detail page title layout is not appropriate  

### ISSUE THREAD

**Issue by naina-verma** [almighty/almighty-ui#271]
Clicked on Open any issue , View detail page title(Header) layout is broken on firefox and chrome both
![screenshot from 2016-11-07 09-24-42](https://cloud.githubusercontent.com/assets/19172870/20046073/3ee6fb08-a4cc-11e6-955e-67e7f8ae330d.png)

**Comment by sanbornsen** [comment]
Which branch you are looking at?

**Comment by ldimaggi** [comment]
alm-ui-208-uxdetailview

**Comment by nimishamukherjee** [comment]
@naina-verma the details page has been updated. It is now a slide out panel.
Hence closing this issue.
