### ISSUE TITLE
Work Item Field Edit stays in Edit mode when swapping between Work Items (Desktop)

### ISSUE THREAD

**Issue by aslakknutsen** [almighty/almighty-ui#274]
## Reproduce

* Go to http://demo.almighty.io/work-item-list/detail/47
* Click edit Title
* Select another work item from the list behind the slide

## Expected Result

* The title field is displayed normally on the newly selected item

## Actual Result

* The title field is still in edit mode on the newly selected item

**Comment by mindreeper2420** [comment]
This also occurs with the Description field.
