### ISSUE TITLE
WorkItemTypes API is called twice during first detail view

### ISSUE THREAD

**Issue by aslakknutsen** [almighty/almighty-ui#276]
## Reproduce

* Open http://demo.almighty.io/work-item-list/detail/50

## Expected result

* WorkItemTypes API called once with Auth

## Actual Result

* WorkItemTypes API called twice, once _without_ Auth and once _with_ Auth

**Comment by sanbornsen** [comment]
I did it purposely, thinking we'll have separate API endpoints for status and types in future. So, I have two separate functions written, even though the response currently have both the data.

**Comment by nimishamukherjee** [comment]
PR #299 merged hence closing this issue.
