### ISSUE TITLE
Outline Around Description Field

### ISSUE THREAD

**Issue by mindreeper2420** [almighty/almighty-ui#278]
According to the [Visual Design](https://redhat.invisionapp.com/share/ZE991DOJ6#/195986245_A-0400-Details_Panel), there should not be an outline of the Description field, unless it is in the active/edit state.

![descriptionoutline](https://cloud.githubusercontent.com/assets/4032718/20103930/db9324d6-a599-11e6-8c1b-bdf1e6c68427.png)

**Comment by sanbornsen** [comment]
Then where do we fit the edit icon? We don't have the border if you are not logged in.

**Comment by mindreeper2420** [comment]
@sanbornsen the edit icons only appears when you are editing the field. There should be a set of hover interactions/visuals around inputs on desktop.

Visuals: https://redhat.invisionapp.com/share/DF8ZQ11R7#/195933772_A-0500-Description_-_Hover

**Comment by sanbornsen** [comment]
Okay, so tell me if I am wrong : 

- User hovers over the description.
- A border with that edit icon appears.
- Clicking on the box or the edit icon would make the border highlighted with light blue.
- And user can edit.

**Comment by mindreeper2420** [comment]
@sanbornsen correct 👍

**Comment by sanbornsen** [comment]
@mindreeper2420 I have made the changes, but did you consider the mobile scenario? Because there is no hover in mobile. So, first two point in the flow I had confirmed in the last comment, i.e. 
* User hovers over the description.
* A border with that edit icon appears.
will not be there in mobile.

**Comment by mindreeper2420** [comment]
@sanbornsen 
* Yes, mobile was considered with the lack of hover, but the nature of mobile usage does not mandate any kind of action around that. We are actively working on methods for giving visuals queues for editable fields on mobile.

* Correct, that is not there on mobile, due to spacing constraints.
