### ISSUE TITLE
Active State Identifiers

### ISSUE THREAD

**Issue by mindreeper2420** [almighty/almighty-ui#279]
According to the Visual Design, the active state of an input should be represented by a light blue border with light blue shadowing. Currently, there is an inconsistency between the Title and Description regarding this visual.

* Visual Design for Title
![item details - update 2x](https://cloud.githubusercontent.com/assets/4032718/20104100/abf6756a-a59a-11e6-82ec-3418a5ba378e.png)

* Visual Design for Description
![a-0500-description_-_hover](https://cloud.githubusercontent.com/assets/4032718/20104255/4be1c89a-a59b-11e6-83d7-c02fcc87751c.png)

* [PatternFly form input design guidelines](http://www.patternfly.org/pattern-library/forms-and-controls/forms/#_design)

Title input has no highlighting:
![screen shot 2016-11-08 at 10 06 14 am](https://cloud.githubusercontent.com/assets/4032718/20104196/0c55a37c-a59b-11e6-9169-517be230613c.png)

Description input only has dark blue outline:
![screen shot 2016-11-08 at 10 06 21 am](https://cloud.githubusercontent.com/assets/4032718/20104202/1133f74a-a59b-11e6-9596-f0c803bdd0ed.png)

**Comment by sanbornsen** [comment]
@mindreeper2420 I believe this issue is just to change the color of title field's bottom border to light blue from black.

**Comment by mindreeper2420** [comment]
@sanbornsen This is to change the border color, add the proper shadowing and making sure that the font sizes/typography stays consistent. It is also the make sure that the hover styles, as dictated in the visual design, are met.

An additional item I noticed is that when the Title is in an active/editable state, the font size increases and the weight increases. This is not the case in the visual designs.

**Comment by nimishamukherjee** [comment]
@mindreeper2420 can you confirm the visual design URL. We followed https://redhat.invisionapp.com/share/M896L20V2#/screens/201494154 (got this link from Brian's email sent to almighty-public list)
This did not have the shadow for the header. Also it did not capture the title edit behaviour.

Can you confirm if we can go ahead with the changes you have mentioned above?

**Comment by mindreeper2420** [comment]
@nimishamukherjee what are you referring to with 'shadow for the header'?

The title edit behavior is the same (minus the complete box surrounding the text) as all of the other edit inputs. The pattern shown for the edit description is the pattern for all edits (see PatternFly as well for how edit visuals are handled).

http://www.patternfly.org/pattern-library/forms-and-controls/forms/#_design

**Comment by nimishamukherjee** [comment]
@mindreeper2420 thanks for the PatternFly link. I will update the title text accordingly.

In the above mobile image, the detail panel header (close icon, type, and save icon) has a box shadow, I was referring to that. 
In your earlier comment you has mentioned - sanbornsen This is to change the border color, add the proper shadowing and making sure .....
I assumed proper shadowing was referring to the header box shadow.

**Comment by nimishamukherjee** [comment]
PR #334 merged. Closing this issue.
