### ISSUE TITLE
No Character limit/Wordwrap on edit for title of workitem :: Firefox

### ISSUE THREAD

**Issue by naina-verma** [almighty/almighty-ui#283]
No Character limit for title , due to long title of workitem display page goes to long scroll. 
It should show word wrap it edit/view mode. Because for long title user need to scroll right to extreem right end
![screenshot from 2016-11-09 12-31-54](https://cloud.githubusercontent.com/assets/19172870/20129810/877624a4-a678-11e6-8731-d83063ddb164.png)
![screenshot from 2016-11-09 12-36-57](https://cloud.githubusercontent.com/assets/19172870/20129911/40f60ce6-a679-11e6-9cd7-d155d40c4220.png)

**Comment by naina-verma** [comment]
@sanbornsen , this issue reproduced in Firefox browser only (chrome is fine)

**Comment by sanbornsen** [comment]
@SMahil can you please take a look on it?

**Comment by nimishamukherjee** [comment]
@naina-verma can you verify if this has been fixed?

**Comment by naina-verma** [comment]
LGTM! verified

**Comment by sanbornsen** [comment]
Looks all good and verified, hence closing this.
