### ISSUE TITLE
Develop the UI for setting/unassign a user as assignee

### ISSUE THREAD

**Issue by nimishamukherjee** [almighty/almighty-ui#288]
Story reference - https://github.com/almighty/almighty-core/issues/341

On the work item's detail page, the user should be able assign and unassign a user as the assignee.

Mobile wireframe - https://redhat.invisionapp.com/share/838XGP02H#/screens
Desktop wireframe - https://redhat.invisionapp.com/share/2D92EG6BH#/screens/199589080_AssignSimple-DT-001

**Comment by mindreeper2420** [comment]
The wireframes have been updated with a simplified version that will fit within this Sprint cycle. Please use these as the primary reference:

[Desktop](https://redhat.invisionapp.com/share/UT99VRINZ#/203937099_AssignUser_-_001)
[Mobile](https://redhat.invisionapp.com/share/RZ99VR9B9#/203654292_1)

Also, the UXD Issue is located here: https://github.com/almighty/almighty-ux/issues/53
