### ISSUE TITLE
Navigating from one associated work item to another

### ISSUE THREAD

**Issue by harrybabu** [almighty/almighty-ui#290]
Story reference - https://github.com/almighty/almighty-core/issues/306

**Comment by joshuawilson** [comment]
@harrybabu if you are working on this, you should assign it to your self.

**Comment by joshuawilson** [comment]
@harrybabu @mindreeper2420 is this done?

**Comment by Mgranfie** [comment]
This was not a requirement that we designed for., so there is no current
solution designed out for this. We list the links but the navigation
between them was not addressed. I have created a story for our next sprint,
we do not have a resource to hop on this in this sprint.

-Monica

**Comment by sanbornsen** [comment]
@Mgranfie @mindreeper2420 any update on this? Can we have a discussion?

**Comment by Mgranfie** [comment]
Hi Suidpta,

Konrad and I worked on this and if you check the comments on the story, the
history of the discussion and solutions should be there.

Any questions lmk.
Thanks,
Monica

**Comment by nimishamukherjee** [comment]
PR #529 merged. Closing this task.
