### ISSUE TITLE
Delete associated work items

### ISSUE THREAD

**Issue by harrybabu** [almighty/almighty-ui#291]
Story reference - https://github.com/almighty/almighty-core/issues/306

**Comment by joshuawilson** [comment]
@harrybabu if you are working on this, you should assign it to your self.

**Comment by joshuawilson** [comment]
@harrybabu @mindreeper2420 is this done? Can we close this?

**Comment by mindreeper2420** [comment]
@joshuawilson. Unknown. There is no way for @almighty/uxd to verify this at the moment.

**Comment by joshuawilson** [comment]
@mindreeper2420 sorry, I missed the word "associated". I was just thinking of deleting a workItem.

**Comment by harrybabu** [comment]
Done. As code got pushed to master.
