### ISSUE TITLE
As a user I want to be able to create a new work item.

### ISSUE THREAD

**Issue by joshuawilson** [almighty/almighty-ui#3]
Using the Angular 2 structure for components create a form that allows users to create a work item. 

This design is the display form and is the closest design we have for the empty create form. Until we get a new design we can use it as a template. https://redhat.invisionapp.com/share/HF86WI2GY#/screens/181584065

**Comment by nimishamukherjee** [comment]
Issue has been resolved. PR has been merged. Hence closing the issue.
