### ISSUE TITLE
Two scrollbars are seen on the work item list page

### ISSUE THREAD

**Issue by nimishamukherjee** [almighty/almighty-ui#309]
Two scrollbars are seen on the work item list page - http://demo.almighty.io/work-item-list
![twoscrollbars](https://cloud.githubusercontent.com/assets/1892722/20217313/4d40f268-a845-11e6-913f-0567848b6dda.png)

**Comment by nimishamukherjee** [comment]
@almighty/uxd is it okay to have two scrollbars?

**Comment by mindreeper2420** [comment]
@nimishamukherjee there should be just one scrollbar. The list should not have it's own scrollbar.

**Comment by nimishamukherjee** [comment]
PR #333 merged. Issue resolved, hence closing the bug.
