### ISSUE TITLE
Edit Icon Persistent on Title Field

### ISSUE THREAD

**Issue by mindreeper2420** [almighty/almighty-ui#311]
The Title field should have the same interaction as the description now does in production (11/11/16 @ 10:32am EDT). I.E. the icon appears on hover over the title, indicating that it is editable. The icon should not be persistent, as it takes up unnecessary space and is not consistent with the designs.

<img width="369" alt="screen shot 2016-11-11 at 10 33 43 am" src="https://cloud.githubusercontent.com/assets/4032718/20220131/58f29bf2-a7fa-11e6-8163-db51d506c72f.png">

**Comment by nimishamukherjee** [comment]
Pr #318 merged hence closing this issue.
