### ISSUE TITLE
Planner items dropdown should be in readonly mode without login

### ISSUE THREAD

**Issue by naina-verma** [almighty/almighty-ui#329]
Planner items dropdown should be in readonly mode without login
I have checked in chrome and firefox , Workitem type / Planner items dropdown slide down when user is not logged In.
![screenshot from 2016-11-21 12-19-25](https://cloud.githubusercontent.com/assets/19172870/20473215/2ac1eec0-afe5-11e6-8d80-809ce02d160d.png)

**Comment by joshuawilson** [comment]
@sanbornsen @naina-verma is this fixed? Can we close this?

**Comment by naina-verma** [comment]
@joshuawilson , verified !!
