### ISSUE TITLE
WorkItem type dropdown shows up an extra label "planneritem"

### ISSUE THREAD

**Issue by naina-verma** [almighty/almighty-ui#330]
WorkItem type dropdown shows up an extra label "planneritem"
![screenshot from 2016-11-21 12-22-58](https://cloud.githubusercontent.com/assets/19172870/20473251/643f6a56-afe5-11e6-9cbf-15755cdef240.png)

**Comment by tsmaeder** [comment]
This is related to https://github.com/almighty/almighty-core/issues/492

**Comment by naina-verma** [comment]
@tsmaeder , @sanbornsen ,
Now this extra label appears in some other index of drop down
![screenshot from 2016-11-28 12-50-13](https://cloud.githubusercontent.com/assets/19172870/20659381/455a6fc6-b569-11e6-8c00-60a016b9ad4a.png)

**Comment by nimishamukherjee** [comment]
@naina-verma can you check this - there is an icon associated with planner. This is a new work item type.

**Comment by aslakknutsen** [comment]
@nimishamukherjee There is no need to add icons to 'planneritem'. It should never be returned from the server in this context.

**Comment by naina-verma** [comment]
@nimishamukherjee , Working fine now !
