### ISSUE TITLE
Functional tests for unauthenticated user

### ISSUE THREAD

**Issue by naina-verma** [almighty/almighty-ui#335]
Functional tests for unauthenticated user
- Test if user is not authenticated can view almighty in read only
- Test Quick add work item should not be visible
- Test user should not be able update the work item type
- Test user should not be able to update the work item state
- Test user should not be able to Delete any work item

**Comment by naina-verma** [comment]
#345 PR is linked to this !

**Comment by joshuawilson** [comment]
@naina-verma can we close this?

**Comment by naina-verma** [comment]
@joshuawilson , closing it ,as PR is merged.
Thanks
