### ISSUE TITLE
Bug: Remove Description from List View

### ISSUE THREAD

**Issue by mindreeper2420** [almighty/almighty-ui#338]
Per UX Designs, there should not be a description in the list view.

UX Visual Design: https://redhat.invisionapp.com/share/T89G321KQ#/195933683_A-0100

**Incorrect View:**
![screen shot 2016-11-22 at 1 56 09 pm](https://cloud.githubusercontent.com/assets/4032718/20537523/73c08880-b0bb-11e6-802d-8dc55fdd8ea0.png)

**Correct View:**
![screen shot 2016-11-22 at 1 56 43 pm](https://cloud.githubusercontent.com/assets/4032718/20537552/863a58b0-b0bb-11e6-9548-bc3b86cde528.png)

**Comment by joshuawilson** [comment]
@SMahil can you please look into this.
