### ISSUE TITLE
Use of nodejs 6 when rhel/centos only have nodejs4

### ISSUE THREAD

**Issue by maxandersen** [almighty/almighty-ui#34]
how do we handle that nodejs is not available on rhel in the version we use ? 

This issue is just to track what we know about the situation - not to say we have use nodejs4, we got options.

@kbsingh did you have some context/info on what exactly is available ?

@joshuawilson is nodejs 6 a hard requirement ?

**Comment by kbsingh** [comment]
For now, in the immediate term lets carry our own nodejs6. We just need to make sure we test the integration points with the other services on our own.

**Comment by mindreeper2420** [comment]
The NodeJS versioning might be an issue in situations other than RHEL, due to the LTS nature of NodeJS 4. I’ve been in situations before where only the LTS versions are allowed on systems. Just an FYI :-)

-Adam

**Comment by maxandersen** [comment]
this is for now just for building, not for running.

**Comment by joshuawilson** [comment]
I will take some time to try and see if it will build on the version supported in RHEL. @kbsingh can you please confirm the exact version supported?

**Comment by joshuawilson** [comment]
Angular 2 will not build on Node 4. We will continue to use Node 6.

**Comment by kbsingh** [comment]
we should have nodejs-6 available on CentOS/RHEL in the coming weeks, once that hits, we should try and rebase to and track that version.
