### ISSUE TITLE
User assignee list design is broken if there is no name for the user

### ISSUE THREAD

**Issue by sanbornsen** [almighty/almighty-ui#341]
This is a very rare case scenario, but if there is no name for an user the design is broken.

<img width="270" alt="screen shot 2016-11-23 at 9 42 22 am" src="https://cloud.githubusercontent.com/assets/2410474/20551030/a1fa0928-b161-11e6-857e-b3a7eedb5685.png">

**Comment by nimishamukherjee** [comment]
PR #343 merged. Issue resolved, hence closing the bug.
