### ISSUE TITLE
Display story creator on new work items

### ISSUE THREAD

**Issue by baijum** [almighty/almighty-ui#351]
As part of "Story Creator (User) on new Work Items" story: https://github.com/almighty/almighty-core/issues/500 the UI should display the creator name on the work items.

**Comment by Mgranfie** [comment]
@nimishamukherjee Reporter Name + Avatar, as the "Creator" should both be displayed. For lack of a wireframe, in the vision based designs, there is an example of how these pieces will all fit together. I hope this helps. LMK any questions...
https://redhat.invisionapp.com/share/Z97SNZ1KY#/176876445_Small_Card_V8_Hover

**Comment by bdellasc** [comment]
Included the placement of the "Creator" info in the work item details pane as part of the icons work. I ran the placement by @Mgranfie and @Essjaysee. You can see the [mockup and spec here](https://redhat.invisionapp.com/share/2F9N0A7WN). Thanks!

**Comment by nimishamukherjee** [comment]
PR #401 merged. Closing this task.
