### ISSUE TITLE
Dialog-based creation of work items

### ISSUE THREAD

**Issue by nimishamukherjee** [almighty/almighty-ui#352]
Develop the UI for dialog-based creation of work Items - https://github.com/almighty/almighty-core/issues/501

**Comment by Mgranfie** [comment]
@nimishamukherjee noticed that the InVision link was not on this story. Let me know if this solution is something you have not seen yet... thanks.

https://redhat.invisionapp.com/share/Y39KFTAE7

**Comment by nimishamukherjee** [comment]
PR #508 merged. Hence closing this issue.
