### ISSUE TITLE
"<" is taken as incomplete HTML tag for create/update workitem

### ISSUE THREAD

**Issue by naina-verma** [almighty/almighty-ui#357]
"<" and ">" is taken as incomplete HTML tag for create/update workitem
Step to reproduce

- Create / update the workitem with "<",">" and save
- Next time when you go to update title/Description it doesnot shows up as expected 
![screenshot from 2016-11-25 15-21-52](https://cloud.githubusercontent.com/assets/19172870/20623383/4cc60eca-b32d-11e6-869c-9e2f113b808b.png)
![screenshot from 2016-11-25 15-21-59](https://cloud.githubusercontent.com/assets/19172870/20623398/611708b6-b32d-11e6-8c1b-6e9d39ffb7f9.png)

**Comment by sanbornsen** [comment]
<select></select>
