### ISSUE TITLE
To long horizontal scrollbar  

### ISSUE THREAD

**Issue by naina-verma** [almighty/almighty-ui#362]
To long horizontal scrollbar  
I have installed today's almighty-ui master , it shows up horizontal scrollbar more than expected design.
![screenshot from 2016-11-28 12-41-15](https://cloud.githubusercontent.com/assets/19172870/20659273/b18ef758-b568-11e6-8f67-beb75263f670.png)

**Comment by sanbornsen** [comment]
I think, we fixed it earlier. @SMahil can you have a look at it?
@naina-verma please specify the browser, if it's happening only on FF or Chrome.

**Comment by SMahil** [comment]
sure @sanbornsen

**Comment by naina-verma** [comment]
@sanbornsen , @SMahil , its not reproduced now !
Closing issue

**Comment by naina-verma** [comment]
@sanbornsen , @SMahil , its not reproduced now !
Closing issue
