### ISSUE TITLE
The AssignTo List is some times missing 'me' 

### ISSUE THREAD

**Issue by aslakknutsen** [almighty/almighty-ui#370]
This is not directly a 'user is not signed in issue' since the navigation bar says 'logout' and the user is allowed to assign/edit the issue to begin with. Not sure how to reproduce it. (sporadically happens, possible related to some timeout?)

![screenshot from 2016-11-29 14-45-10](https://cloud.githubusercontent.com/assets/132158/20712021/ab4fb3e8-b642-11e6-9b0e-dd5cd3716ed3.png)

**Comment by joshuawilson** [comment]
I think I found out how to reproduce this.
If you add something via the quick add and then open an item and check the assignee, "me" is missing.
