### ISSUE TITLE
Bug: Logged In User Icon Not Always Displayed

### ISSUE THREAD

**Issue by mindreeper2420** [almighty/almighty-ui#371]
When navigating to demo.almighty.io on a browser that I have already logged into the site with, my user icon does not appear in the top right, as expected. It only appears when I navigate away from the Work Item List and then navigate back to it.

<img width="1920" alt="screen shot 2016-11-29 at 8 10 59 pm" src="https://cloud.githubusercontent.com/assets/4032718/20735755/34f39056-b670-11e6-9b1a-ef6cea0cc5dc.png">

**Comment by SMahil** [comment]
@mindreeper2420 if u click on bell icon username and avatar are coming then

**Comment by mindreeper2420** [comment]
@smahil - my name did appear when I clicked that, but if I navigate away from the page and then back again, it appears without me clicking the bell. The inconsistency and just randomly clicking to find my name are what caused this to be filed. 

Also, the bell is an alert or message icon, not a user profile icon.

**Comment by sanbornsen** [comment]
@mindreeper2420 @SMahil it's nothing to do with the Bell icon. It's coming only after navigating for the first time, either clicking on the bell icon or any recent child link to the root. This is a bug. I fixed it and raised a PR, waiting for @joshuawilson to review. I must say, nice found @mindreeper2420 .
