### ISSUE TITLE
Bug: Missing User in Assign User Search

### ISSUE THREAD

**Issue by mindreeper2420** [almighty/almighty-ui#374]
As a user logged into the system, I am unable to find myself by performing a search of the user list under the 'Assign User' feature in Work Item Detail.

<img width="966" alt="screen shot 2016-11-29 at 8 48 43 pm" src="https://cloud.githubusercontent.com/assets/4032718/20736544/3e4634ce-b675-11e6-8d7e-66db1dccacf1.png">

**Comment by joshuawilson** [comment]
Does your user name appear without filtering?

**Comment by mindreeper2420** [comment]
No, it does not.

**Comment by joshuawilson** [comment]
I think you may have duplicated #370

**Comment by mindreeper2420** [comment]
Possibly? That one looks like it is pointing out the missing 'Assign to Me' feature...?

**Comment by joshuawilson** [comment]
I think they are. We can keep this open and just close both when it gets fixed.
