### ISSUE TITLE
Consume jsonapi based WorkItem List

### ISSUE THREAD

**Issue by pranavgore09** [almighty/almighty-ui#377]
This task should integrate the work done in [core#528](https://github.com/almighty/almighty-core/issues/528).

Adapt the changes and read relationships to pick up `assignee` of WorkItem.

Display `assignee` in the list view as per [UX design](https://redhat.invisionapp.com/share/T89G321KQ#/195933683_A-0100)

**Comment by joshuawilson** [comment]
This was completed in PR #481 and #486
