### ISSUE TITLE
Filter UI based on Assignee

### ISSUE THREAD

**Issue by sanbornsen** [almighty/almighty-ui#384]
Based on the status of the filter (assigned to me) button, some extra parameters need to be added with the workitem.2 API and get the filtered data and render it to the list.

**Comment by joshuawilson** [comment]
This might be a great issue that can be broken out into smaller tasks. What do you think?

**Comment by sanbornsen** [comment]
This issue is resolved on PR - https://github.com/almighty/almighty-ui/pull/485
