### ISSUE TITLE
Bug: Viewing Related Work Items Throws Exceptions

### ISSUE THREAD

**Issue by mindreeper2420** [almighty/almighty-ui#406]
When clicking on 'Related planner item' in the Work Item Linking bar, an exception is thrown. The UI still displays the linking input option.

When I try to click on another item in the Work Item List, the URL changes (http://demo.almighty.io/work-item-list/detail/47 becomes http://demo.almighty.io/work-item-list/detail/256), but the UI does not show me the proper Work Item Detail information or highlighted row.

![screen shot 2016-12-01 at 1 04 57 pm](https://cloud.githubusercontent.com/assets/4032718/20806022/3b2c2ef8-b7c7-11e6-8383-b020ea9ed2a5.png)

**Comment by mindreeper2420** [comment]
Note - I have to refresh my screen in order for the exception to clear and continue to navigate through the work item list.

**Comment by joshuawilson** [comment]
This was fixed in #403 and #405
