### ISSUE TITLE
Support for HTML5 (History API) pushState in the backend

### ISSUE THREAD

**Issue by baijum** [almighty/almighty-ui#45]
For now I have send a pull request (#41) to disable history API and use hash based routing.

But for a better URL navigation, we need to support History API.

Ref: https://developer.mozilla.org/en-US/docs/Web/API/History_API#The_pushState()_method

The `index.html` should be the default target for all request in the web app.  We need a custom Nginx configuration to support this.

Ref. http://stackoverflow.com/questions/13812550/configuring-nginx-for-single-page-website-with-html5-push-state-urls

BTW, if we are going to implement #44 , I think the configuration will become much saner.

**Comment by baijum** [comment]
cc. @kbsingh @kwk

**Comment by baijum** [comment]
@sanbornsen Is this issue resolved recently?

**Comment by sanbornsen** [comment]
Yes, hence closing it.
Here is the PR in UI -  https://github.com/almighty/almighty-ui/pull/250
