### ISSUE TITLE
Remove hardcoded references to ".2" API in services file

### ISSUE THREAD

**Issue by ldimaggi** [almighty/almighty-ui#450]
See:

https://github.com/almighty/almighty-ui/blob/master/src/app/work-item/work-item.service.ts

**Comment by sanbornsen** [comment]
@ldimaggi once we migrate completely from **workitems** to **workitems.2** then the **workitems.2** will become **workitems**, so it's just a matter of time.

**Comment by joshuawilson** [comment]
@sanbornsen is this done?

**Comment by sanbornsen** [comment]
Yes, we can close this.
