### ISSUE TITLE
FTBS for prod

### ISSUE THREAD

**Issue by kbsingh** [almighty/almighty-ui#47]
the present codebase does not build for prod deployments. 
$ git clone https://github.com/almighty/almighty-ui
$ export API_URL="http://demo.api.almighty.io/api/"
$ export PUBLIC_PATH="http://demo.almighty.io/"
$ npm install
$ npm run build:prod
is expected to produce a working app, however fails with :

npm ERR! Linux 3.10.0-327.18.2.el7.x86_64
npm ERR! argv "/usr/local/node/node-v6.3.1-linux-x64/bin/node" "/usr/local/node/node-v6.3.1-linux-x64/bin/npm" "run" "build:prod"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! almighty-ui@0.0.4 build:prod: `webpack --config config/webpack.prod.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the almighty-ui@0.0.4 build:prod script 'webpack --config config/webpack.prod.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the almighty-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack --config config/webpack.prod.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs almighty-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls almighty-ui
npm ERR! There is likely additional logging output above.
npm ERR! Linux 3.10.0-327.18.2.el7.x86_64
npm ERR! argv "/usr/local/node/node-v6.3.1-linux-x64/bin/node" "/usr/local/node/node-v6.3.1-linux-x64/bin/npm" "run" "build:prod"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! path npm-debug.log.3697563534
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open 'npm-debug.log.3697563534'
npm ERR! enoent ENOENT: no such file or directory, open 'npm-debug.log.3697563534'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent

**Comment by kbsingh** [comment]
merging in https://github.com/almighty/almighty-ui/pull/41 has no impact, we still FTBS

**Comment by baijum** [comment]
@kbsingh After mergin #41 , a web server like nginx would be fine to serve the content. I have updated Dockerfile to support this in #42
