### ISSUE TITLE
Use new relational API for work item linking

### ISSUE THREAD

**Issue by sanbornsen** [almighty/almighty-ui#489]
Currently we are using an end pont to fetch all the work item linking and then filtering it in front end.
We need to update this to the new relational API for work item.
http://demo.api.almighty.io/api/workitems/{id}/relationships/links

**Comment by aslakknutsen** [comment]
UI should follow link provided in workitem/x {data.relationships.links.links.self}

(Yes, double links. It's the links for the links. @kwk maybe rename to workitemlinks?)

**Comment by sanbornsen** [comment]
@aslakknutsen we don't have that yet, do we?
