### ISSUE TITLE
Unable to delete wokitems 

### ISSUE THREAD

**Issue by naina-verma** [almighty/almighty-ui#498]
Unbale to delete wokitems , on http://demo.almighty.io/work-item-list
Steps to reproduce 
- Try to delete new or already existing work item 
- Expected : WI should deleted , Actual : Gives 404 
API reference should point to workitems instead of workitems.2 
`Request URL:http://demo.api.almighty.io/api/workitems.2/210
Request Method:OPTIONS
Status Code:404 Not Found
Remote Address:8.43.84.247:80
Response Headers
view source
Content-Encoding:gzip
Content-Length:130
Content-Type:application/vnd.api+json
Date:Mon, 12 Dec 2016 05:52:31 GMT
Set-Cookie:OPENSHIFT_EDGE_almighty_api-demo-ssl_SERVERID=7cf26085469d40aca0365c4e66ad2eb6; path=/; HttpOnly; Secure
Vary:Accept-Encoding
`
![core1](https://cloud.githubusercontent.com/assets/19172870/21090229/2ca73df0-c064-11e6-843f-35cdb06cbd68.jpg)

**Comment by baijum** [comment]
The API end point should be `workitems` not `workitems.2`

**Comment by sanbornsen** [comment]
Thanks @naina-verma for reporting this.
