### ISSUE TITLE
As a user I want to be able to update / edit a work item.

### ISSUE THREAD

**Issue by joshuawilson** [almighty/almighty-ui#5]
Using the Angular 2 structure for components create a form that allows users to update or edit a work item.

This design is the display form and is the closest design we have for the editable form. Until we get a new design we can use it as a template. https://redhat.invisionapp.com/share/HF86WI2GY#/screens/181584065

**Comment by nimishamukherjee** [comment]
Issue has been resolved. PRs - #22 and #28 have been merged. Hence closing the issue.
