### ISSUE TITLE
Deployment acceptance criteria should be testable

### ISSUE THREAD

**Issue by kbsingh** [almighty/almighty-ui#50]
We need a base set of acceptance tests to run against the app for use in the build, release process.

These tests would run after the app is built and pushed into the relevant pod, as a way to verify that the app is now promoteable to productoin loads.

**Comment by joshuawilson** [comment]
We have @ldimaggi putting some of this together with @bartoszmajsak and we have @nimishamukherjee setting up a test framework too. 

When any of you make progress here, please post a note about the PR.

**Comment by ldimaggi** [comment]
+1 - We'll start defining a set of tests - this is a good side topic for the Sept 12-16 meeting too.

**Comment by michaelkleinhenz** [comment]
Should the verification span the full application or just the ui container? If it spans the full application, this is a larger task, involving setting up a E2E test framwork. I would suppose we currently looking only at functional tests local to the ui container in this sprint.

**Comment by ppitonak** [comment]
Verification of UI container should be the first step. Since every merge goes potentially to production, E2E tests are a must.

**Comment by michaelkleinhenz** [comment]
I just submitted PR #92, which adds the framework for functional tests plus integration in the deploy/PR processes.
