### ISSUE TITLE
"created at:" looks distorted on Detail view page

### ISSUE THREAD

**Issue by naina-verma** [almighty/almighty-ui#524]
"created at:" looks distorted on Detail view page 
![screenshot from 2016-12-15 12-24-12](https://cloud.githubusercontent.com/assets/19172870/21214573/87eb0c78-c2c1-11e6-889f-b166db9a75d8.png)

**Comment by bdellasc** [comment]
Included the placement of the "Created" info in the work item details pane as part of the icons work. I ran the placement by @Mgranfie and @Essjaysee. You can see the [mockup and spec here](https://redhat.invisionapp.com/share/2F9N0A7WN).

As far as the rules, exact wording and behavior of the "Created" data, we're working on that as part of a story this UX sprint (124c). We'll report out decisions at the conclusion of the sprint next week. Thanks!

**Comment by Mgranfie** [comment]
:) thanks B!

**Comment by SMahil** [comment]
@bdellasc Are we following the same mockup design for mobile view
