### ISSUE TITLE
No height,width wrapper defined for avatar in list view 

### ISSUE THREAD

**Issue by naina-verma** [almighty/almighty-ui#525]
No height,width wrapper defined for avatar in list view.
There should be container having defined height and width of avatar in wi list view.
![screenshot from 2016-12-15 15-48-37](https://cloud.githubusercontent.com/assets/19172870/21220331/62a1205c-c2de-11e6-97ca-6e261fd1583d.png)
![screenshot from 2016-12-15 15-51-24](https://cloud.githubusercontent.com/assets/19172870/21220332/62a6043c-c2de-11e6-951e-9cb9df4e4aad.png)

**Comment by bdellasc** [comment]
@naina-verma @Mgranfie In the [visual specs](https://redhat.invisionapp.com/share/NU8YPHLJP), screen #3: The avatar in the list is spec'd as 28px x 28px. The color and thickness of the bounding box is also spec'd there. Let me know if you have any other questions. Thanks!

**Comment by naina-verma** [comment]
@bdellasc , That looks like a UI bug, height and width is not implemented as the way it shows up in visual specs.
