### ISSUE TITLE
Empty drop down of Filter shows up, for unauthorized user

### ISSUE THREAD

**Issue by naina-verma** [almighty/almighty-ui#526]
Empty drop down for Filter shows up for unauthorized user
![screenshot from 2016-12-15 18-04-17](https://cloud.githubusercontent.com/assets/19172870/21224234/24f3fc58-c2f1-11e6-8702-808ffc5628a4.png)

**Comment by nimishamukherjee** [comment]
PR #534 merged. Closing this bug.
