### ISSUE TITLE
"Assign to me" filter is present, but does not seem to do anything

### ISSUE THREAD

**Issue by ldimaggi** [almighty/almighty-ui#527]
At: http://demo.almighty.io, the "Assign to me" filter allows the user to select it, but it does not actually perform the filtering.

See screencast here:
https://dl.dropboxusercontent.com/u/12067552/Screencasts/ALMighty_filter.webm

**Comment by aslakknutsen** [comment]
The backend had not deployed it yet 😀

**Comment by nimishamukherjee** [comment]
@ldimaggi this is working now. Can you please verify this?

**Comment by ldimaggi** [comment]
Just verified it here-  http://demo.almighty.io/work-item-list
