### ISSUE TITLE
Cannot create a new workitem through the new detailed dialog

### ISSUE THREAD

**Issue by ldimaggi** [almighty/almighty-ui#538]
See referenced screencast - the dialog screen goes blank when the exit button is clicked.

https://dl.dropboxusercontent.com/u/12067552/Screencasts/ALMighty_new_wi_dialog.webm

**Comment by nimishamukherjee** [comment]
@ldimaggi PR #596 merged. Please review.

**Comment by naina-verma** [comment]
@nimishamukherjee , I have verified this issue on behalf of @ldimaggi .
It works !

**Comment by nimishamukherjee** [comment]
Thanks @naina-verma ! Closing this issue.
