### ISSUE TITLE
In the new detailed work item creation dialog, the edit icon for the title field is transposed over another icon

### ISSUE THREAD

**Issue by ldimaggi** [almighty/almighty-ui#540]
See the referenced screencast:

https://dl.dropboxusercontent.com/u/12067552/Screencasts/ALMighty_new_dialog_icon_transposed.webm

**Comment by naina-verma** [comment]
Just to add on ,Unable to create new work item by this dialogue too!

**Comment by nimishamukherjee** [comment]
@ldimaggi @naina-verma please verify. PR #584 merged.

**Comment by nimishamukherjee** [comment]
@ldimaggi , @naina-verma please verify

**Comment by naina-verma** [comment]
Verified , Works fine now !
