### ISSUE TITLE
On hover to Add icon for "Add dialogue" there should be title 

### ISSUE THREAD

**Issue by naina-verma** [almighty/almighty-ui#544]
On hover to Add icon for "Add dialogue" there should be title, to indicate for what this add icon for !
- Tooltip would be very helpful for user.
- Size of add icon looks big 
![screenshot from 2016-12-20 11-47-58](https://cloud.githubusercontent.com/assets/19172870/21340119/5226efd4-c6aa-11e6-989a-b8e87ac7c601.png)

**Comment by SMahil** [comment]
@Mgranfie @mindreeper2420 Do we have some design for this or a normal tooltip should work here

**Comment by mindreeper2420** [comment]
@SMahil @Mgranfie I believe it would just be a tooltip. Think of the FAB in Material Design.

**Comment by nimishamukherjee** [comment]
@naina-verma can you verify this fix?

**Comment by naina-verma** [comment]
@nimishamukherjee , @SMahil Works fine now !
