### ISSUE TITLE
Duplicate entry of work item in work item listing

### ISSUE THREAD

**Issue by vikram-raj** [almighty/almighty-ui#546]
* When we directly hit the URL of detail page of any work item then duplicate of that work item is created in the list.

**Comment by debloper** [comment]
Can you please explain the `"directly hit the URL of detail page of any work item"` part?
Which path format you're using to directly hit the work item details page?

**Comment by vikram-raj** [comment]
Refresh the page when workitem detail page is open. or copy-pastes the detail page URL into another tab.
You can try this http://demo.almighty.io/work-item-list/detail/250.

**Comment by debloper** [comment]
Can't reproduce.
Can you create a demo like the one in #438

**Comment by vikram-raj** [comment]
Demo - https://drive.google.com/open?id=0B3RCeh_HGvEPZlNkZElWT293YVU

**Comment by debloper** [comment]
Access requested. You can also make the file sharing setting "readable by everyone with a link".

**Comment by sanbornsen** [comment]
I know the issue. I am taking it over.
