### ISSUE TITLE
Link-item drop down doesn't change dynamically 

### ISSUE THREAD

**Issue by naina-verma** [almighty/almighty-ui#555]
Link-item drop down doesn't change dynamically 
Steps to reproduce 
- Open a detail view Planner work item , click on create link . It will shows up 3 (blocks, tests, relates to ) in dropdown
- Change planner WI to userstory in same detail view ,click on create link . It will shows up 3 (blocks, tests, relates to ) in dropdown.
Expected behavior : it should dynamically update the drop down to "No links type Available" on changing the wi type.
Video Link : https://drive.google.com/a/redhat.com/file/d/0B1qUq_laG6CONC1HbTNNbG5HdW8/view?usp=sharing

**Comment by sanbornsen** [comment]
Nice find @naina-verma . Thanks for reporting. Fixing this.
