### ISSUE TITLE
Header links of link-items should provide detail for respective links

### ISSUE THREAD

**Issue by naina-verma** [almighty/almighty-ui#583]
Header links of link-items should provide detail for respective links

Suppose we have Headers in details view , which have 5 columns (types of links) as blocked by, tests etc...
![header](https://cloud.githubusercontent.com/assets/19172870/21425392/e35ca546-c86e-11e6-97db-6a4a114a50e7.png)
When we click on "blocked by" it should display details for only blocked by link items, Right now its displaying overall items for every link.

Can you provide some inputs for this?

**Comment by sanbornsen** [comment]
@Mgranfie @mindreeper2420 please comment on this.
