### ISSUE TITLE
When built in prod version some css gets messed up

### ISSUE THREAD

**Issue by aslakknutsen** [almighty/almighty-ui#59]
![screenshot from 2016-09-05 02-22-39](https://cloud.githubusercontent.com/assets/132158/18234773/b5fd0622-730f-11e6-993d-0bf57f8f5378.png)

See current deployed v on http://demo.almighty.io/#/work-item-list

**Comment by sanbornsen** [comment]
Following PR has the fix of this issue. https://github.com/almighty/almighty-ui/pull/46
