### ISSUE TITLE
As a user I want to be able to use a predefined work item type.

### ISSUE THREAD

**Issue by joshuawilson** [almighty/almighty-ui#6]
The work items have types and those types define what they will look like and what data they display.

Initially they should have:
  - UserStory
  - Task
  - Bug

**Comment by tsmaeder** [comment]
Can you give us the list of fields you need right now to build your UI?

**Comment by joshuawilson** [comment]
The fields are listed at the beginning of https://github.com/almighty/almighty-core/issues/99

**Comment by joshuawilson** [comment]
This appears to be covered by the current UI implementations.
