### ISSUE TITLE
"No creator found" while creating new WI, is it required to show?

### ISSUE THREAD

**Issue by naina-verma** [almighty/almighty-ui#605]
"No creator found" while creating new WI, is it required to show?

I have query regarding design for creator ,
- If user is creating first time WI is it required to show "Creator : No creator found " on UI ?  we can hide creator field on UI for time of creation of workitem.  
- When the creator fullName doesn't exists ,  core is showing temporarily Github username . So, What is the need of "No creator found" ?

**Comment by debloper** [comment]
There're 2 solutions to this problem that I readily see:

1. **Easy Solution:** Populate that section from the logged in user's details (fullname or username). This is low-struggle choice which doesn't clash with existing UX suggestions (or needs them to update it).
2. **Right Solution:** Question the UX suggestion, and listen to the argument why having an extra field inside the form (which can't be input by the user) is necessary and then draw a conclusion.

But in all certainty, going with 1, while 2 is being figured out would be the best case scenario.

**Comment by naina-verma** [comment]
@almighty/uxd , please provide input on it!

**Comment by mindreeper2420** [comment]
@naina-verma A user must be logged into the system in order to create a new Work Item, so the Creator field is auto populated with the user's information. There should not be a 'No Creator Found' entry in that place. All created items must have a creator. @almighty/uxd

**Comment by naina-verma** [comment]
Thanks for update @almighty/uxd
