### ISSUE TITLE
As a user I want to be able to transition a work item from open to done.

### ISSUE THREAD

**Issue by joshuawilson** [almighty/almighty-ui#7]
There are an unspecified number of states or stages between open and done. At a minimum the work item should show the state it is in and that state should be able to be changed from open to done.

See the design here of the state on the left side https://redhat.invisionapp.com/share/HF86WI2GY#/screens/181584053

**Comment by sanbornsen** [comment]
Issue has been resolved. PR (https://github.com/almighty/almighty-ui/pull/60) has been merged. Hence closing the issue.

**Comment by aslakknutsen** [comment]
Technically UI nor Backend has an understanding of "Transition" at this point, it's currently just a String with an  'allowed' values Enum. To really fulfill this, UI needs to understand the WorkitemType and the Flow that it represent, and the WorkItemType has to be able to describe that Flow :)

e.g. in a Full v only someone from the QE Team is allowed to Transition the state from Resolved to QE Accepted.. Or only a Maintainer can Close and issue. Or you can't Transition from Closed to In Progress.

But, we can create other Issues for the specifics

**Comment by sanbornsen** [comment]
I thought, this much is what we had to do for Alpina release, so closed it assuming it's done for now. 
This is something what I thought as a future scope - 
* There should be an endpoint to fetch the app settings which will be called right before the app starts.
* This settings will have various data including **state_types** which will have different types i.e. New, Done, In Progress etc. along with their label colors and IDs.
* With each workItem there will be a state_type_id associated.

Once we reach there, either we can reopen it or create a new one.

CC: @aslakknutsen
