### ISSUE TITLE
Frame, Header and Footer should match UX designs

### ISSUE THREAD

**Issue by michaelkleinhenz** [almighty/almighty-ui#71]
The frame should match the UX designs, including basic wireframing and responsive configuration.

**Comment by michaelkleinhenz** [comment]
See https://github.com/almighty/almighty-ux/issues/1 for breakpoint info.

**Comment by nimishamukherjee** [comment]
@michaelkleinhenz / @joshuawilson can we close this? We have the frame in place. The new header, menu, and footer could be a new story?
