### ISSUE TITLE
As a user I should be able to login into the application.

### ISSUE THREAD

**Issue by joshuawilson** [almighty/almighty-ui#8]
The login page should be a component version of the PatternFly style. We should be able to use the HTML and CSS in the PatternFly example.

**Comment by tsmaeder** [comment]
With Nimisha...

**Comment by joshuawilson** [comment]
@aslakknutsen can you please update this issue when the backend supports the Login?

**Comment by michaelkleinhenz** [comment]
I think this is a story and should be split up into tasks. I can't see what's the progress here.

**Comment by nimishamukherjee** [comment]
PR #189 merged with master, hence closing this story.
