### ISSUE TITLE
Update to Angular 2.0.0

### ISSUE THREAD

**Issue by joshuawilson** [almighty/almighty-ui#85]

**Comment by sanbornsen** [comment]
I suggest to do this after we merge all of our pending PRs that has to be merged. So that we can see where are all the places, the update is causing problem.

**Comment by joshuawilson** [comment]
I agree. It would also make life hard for everyone else that would have to merge the changes. It is just easier to merge all pending PRs that we can and then do this.

**Comment by ppitonak** [comment]
I'm afraid that you cannot wait for all PRs to be merged... this issue would be blocked forever.
