### ISSUE TITLE
Rename all the selectors in components as the class name.

### ISSUE THREAD

**Issue by sanbornsen** [almighty/almighty-ui#86]
* Two component class having same selector would throw an error. To be on safe side, we should always name the selectors as the class name, that way the chances of such conflict will be minimized.
* Also instead of using **declarations** at **app.module.ts** we can use **directives** in main components to include sub components. That will also help us to minimize the chances of conflict.

The error this problem produces, doesn't have any meaningful message. So, we need to be careful. This looks like a design problem of Angular2. I hope we never run across with a conflict between a selector from global module and local module. I couldn't find a proper solution yet, please post here if anyone can.

**Comment by joshuawilson** [comment]
I believe Angular suggests namespacing all of them. I hadn't done that since we have yet to decide on a name. You are right it could be an issue.  I plan on fixing this when I refactor the UI into multiple repos / modules.

**Comment by joshuawilson** [comment]
@sanbornsen Following the Angular 2 Style guide I went through and renamed all the selectors with the prefix "alm-". Does this answer your concerns. Please review the changes in master.

**Comment by sanbornsen** [comment]
Yes. It does. To be more specific, all the independent component will have pf as prefix and all the components and sub components will have alm as prefix.
