### ISSUE TITLE
Cannot create new work items - on server built from master

### ISSUE THREAD

**Issue by ldimaggi** [almighty/almighty-ui#96]
The save button is being ignored - first spotted this late on September 25 - thx!

**Comment by joshuawilson** [comment]
@ldimaggi I just tried it and I can save with the button and the Enter key. Can you please list the steps to reproduce this bug? Also, refresh too. ;)

**Comment by michaelkleinhenz** [comment]
Have you correctly set/wired a backend? See the readme for details. Also, if not wired, the browser console will output lots of errors..

**Comment by ldimaggi** [comment]
Doh! Yes - forgot export ENV=inmemory

This one can be closed. Thx!
